[2024-10-29T23:08:41.103+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk2 manual__2024-10-29T23:08:40.416167+00:00 [queued]>
[2024-10-29T23:08:41.118+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk2 manual__2024-10-29T23:08:40.416167+00:00 [queued]>
[2024-10-29T23:08:41.119+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:08:41.119+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-10-29T23:08:41.119+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:08:41.140+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-10-29 23:08:40.416167+00:00
[2024-10-29T23:08:41.148+0000] {standard_task_runner.py:55} INFO - Started process 721 to run task
[2024-10-29T23:08:41.152+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag3', 'tsk2', 'manual__2024-10-29T23:08:40.416167+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag3.py', '--cfg-path', '/tmp/tmpoj71is0j']
[2024-10-29T23:08:41.153+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask tsk2
[2024-10-29T23:08:41.282+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag3.tsk2 manual__2024-10-29T23:08:40.416167+00:00 [running]> on host 55e2175811f2
[2024-10-29T23:08:41.421+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag3
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-10-29T23:08:40.416167+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-29T23:08:40.416167+00:00
[2024-10-29T23:08:41.423+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-29T23:08:41.424+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-10-29T23:08:41.452+0000] {subprocess.py:86} INFO - Output:
[2024-10-29T23:08:41.456+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-29T23:08:41.478+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-29T23:08:41.483+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag3, task_id=tsk2, execution_date=20241029T230840, start_date=20241029T230841, end_date=20241029T230841
[2024-10-29T23:08:41.506+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task tsk2 (Bash command failed. The command returned a non-zero exit code 1.; 721)
[2024-10-29T23:08:41.535+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-29T23:08:41.571+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
