[2024-10-29T23:29:33.402+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-10-29T23:29:26.633570+00:00 [queued]>
[2024-10-29T23:29:33.433+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-10-29T23:29:26.633570+00:00 [queued]>
[2024-10-29T23:29:33.433+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:29:33.434+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-10-29T23:29:33.434+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:29:33.471+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-10-29 23:29:26.633570+00:00
[2024-10-29T23:29:33.499+0000] {standard_task_runner.py:55} INFO - Started process 991 to run task
[2024-10-29T23:29:33.509+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'manual__2024-10-29T23:29:26.633570+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmps64uhupe']
[2024-10-29T23:29:33.512+0000] {standard_task_runner.py:83} INFO - Job 100: Subtask tsk4
[2024-10-29T23:29:33.664+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 manual__2024-10-29T23:29:26.633570+00:00 [running]> on host 55e2175811f2
[2024-10-29T23:29:33.815+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=aws@evoluth.com.br
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-10-29T23:29:26.633570+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-29T23:29:26.633570+00:00
[2024-10-29T23:29:33.817+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-29T23:29:33.819+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-10-29T23:29:33.858+0000] {subprocess.py:86} INFO - Output:
[2024-10-29T23:29:33.861+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-29T23:29:33.893+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-29T23:29:33.901+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20241029T232926, start_date=20241029T232933, end_date=20241029T232933
[2024-10-29T23:29:33.930+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 100 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 991)
[2024-10-29T23:29:33.965+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-29T23:29:34.034+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
